apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: your-docker-repo/book-catalog:latest
        ports:
        - containerPort: 80
        env:
        - name: NAME
          value: "World"
        - name: DATABASE_URL
          value: "postgresql://faizan_raza_sit722_part2_user:1l9LroJbAXXXetAdMagaZnSAo8N9kTKp@dpg-crbhkg3tq21c73ciurpg-a.oregon-postgres.render.com/faizan_raza_sit722_part2"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
